### ISSUE TITLE
USB Connection issue

### ISSUE THREAD

**Issue by assada** [PixelyIon/DeckTX#1]
Hi!

I’m using a USB connection with TX and [ELRS Joystick Control](https://github.com/kaack/elrs-joystick-control) as client, and everything works fine.
However, when I use only DeckTX, DeckTX cannot connect via USB to my TX (it sends a ping frame and nothing more).

But! If I first run ELRS Joystick Control and create a link there, and then run DeckTX, everything works in both programs in the same time. As soon as I stop ELRS Joystick Control, DeckTX loses the connection as well. This is very strange behavior.

I’ll try to record a video. https://youtu.be/2H9nUTgomfk

**Comment by PixelyIon** [comment]
Hey there, I suspect this is due to [automatic baud rate detection](https://en.wikipedia.org/wiki/Automatic_baud_rate_detection) not working correctly. I just hardcoded the baud rate in my ELRS FW instead during my initial testing and then never tested without it. ELRS Joystick Control is likely setting up the connection with the right baud rate, which is probably why it works when it's running.

**Comment by assada** [comment]
Possibly. What’s interesting is that when I close "ELRS Joystick Control," DeckTX immediately loses the connection, even though the port should have been configured by ELRS Joystick Control

**Comment by assada** [comment]
I reduced the ping interval and removed the reset. And it worked! I’ll try to figure out later what exactly helped.
https://github.com/assada/DeckTX/pull/1/files#diff-34d21af3c614ea3cee120df276c9c4ae95053830d7f1d3deaf009a4625409ad2

**Comment by PixelyIon** [comment]
Ah, I think it is indeed an issue with autobaud then. It likely needs a continuous stream of bits being sent, and we send pings too infrequently.
